"""SQL queries for the dashboard."""

KPI_QUERY = """
SELECT
    SUM(CASE WHEN STATUS = 'In Progress' THEN 1 ELSE 0 END) AS in_progress,
    COUNT(*) AS total_incidents,
    SUM(CASE WHEN STATUS = 'Pending Approval' THEN 1 ELSE 0 END) AS pending_approval,
    SUM(CASE WHEN STATUS = 'Fix Failed' THEN 1 ELSE 0 END) AS fix_failed,
    SUM(CASE WHEN STATUS = 'Auto Fixed' THEN 1 ELSE 0 END) AS auto_fixed,
    ROUND(SUM(CASE WHEN AUTO_FIX_APPLIED = TRUE THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 1) AS auto_fix_rate,
    ROUND(AVG(CASE WHEN RESOLUTION_TIME IS NOT NULL THEN RESOLUTION_TIME END), 1) AS avg_resolution_time,
    ROUND(SUM(CASE WHEN ROOT_CAUSE IS NOT NULL AND ROOT_CAUSE != '' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 1) AS rca_coverage
FROM CPI_MONITORING.INCIDENTS
"""

STATUS_BREAKDOWN_QUERY = """
SELECT STATUS as status, COUNT(*) as count
FROM CPI_MONITORING.INCIDENTS
GROUP BY STATUS
ORDER BY count DESC
"""

ERROR_DISTRIBUTION_QUERY = """
SELECT ERROR_TYPE as error_type, COUNT(*) as count
FROM CPI_MONITORING.INCIDENTS
GROUP BY ERROR_TYPE
ORDER BY count DESC
"""

TOP_FAILING_ARTIFACTS_QUERY = """
SELECT INTEGRATION_SCENARIO as artifact, COUNT(*) as failure_count
FROM CPI_MONITORING.INCIDENTS
GROUP BY INTEGRATION_SCENARIO
ORDER BY failure_count DESC
LIMIT ?
"""

FAILURE_OVER_TIME_QUERY = """
SELECT
    TO_VARCHAR(CREATED_AT, 'YYYY-MM-DD"T"HH24:00:00') as timestamp,
    COUNT(*) as count
FROM CPI_MONITORING.INCIDENTS
WHERE CREATED_AT >= ADD_SECONDS(NOW(), ?)
GROUP BY TO_VARCHAR(CREATED_AT, 'YYYY-MM-DD"T"HH24:00:00')
ORDER BY timestamp ASC
"""

FAILED_MESSAGES_COUNT_QUERY = """
SELECT COUNT(*) as count FROM CPI_MONITORING.FAILED_MESSAGES
"""

INCIDENTS_LIST_QUERY = """
SELECT ID, SUBSCRIPTION_ID, INTEGRATION_SCENARIO, ERROR_TYPE, STATUS,
       MESSAGE, ROOT_CAUSE, AUTO_FIX_APPLIED, RESOLUTION_TIME,
       TO_VARCHAR(CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS') as CREATED_AT,
       TO_VARCHAR(UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS') as UPDATED_AT
FROM CPI_MONITORING.INCIDENTS
ORDER BY CREATED_AT DESC
LIMIT ? OFFSET ?
"""

FAILED_MESSAGES_LIST_QUERY = """
SELECT ID, SUBSCRIPTION_ID, IFLOW_NAME, STATUS, ERROR_TYPE,
       TO_VARCHAR(CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS') as CREATED_AT
FROM CPI_MONITORING.FAILED_MESSAGES
ORDER BY CREATED_AT DESC
LIMIT ? OFFSET ?
"""
