-- SAP HANA Schema for CPI Monitoring Dashboard

CREATE SCHEMA IF NOT EXISTS CPI_MONITORING;

SET SCHEMA CPI_MONITORING;

CREATE TABLE IF NOT EXISTS INCIDENTS (
    ID NVARCHAR(100) PRIMARY KEY,
    SUBSCRIPTION_ID NVARCHAR(255),
    INTEGRATION_SCENARIO NVARCHAR(255),
    ERROR_TYPE NVARCHAR(255),
    STATUS NVARCHAR(100),
    MESSAGE NVARCHAR(5000),
    ROOT_CAUSE NVARCHAR(5000),
    AUTO_FIX_APPLIED BOOLEAN DEFAULT FALSE,
    RESOLUTION_TIME INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FAILED_MESSAGES (
    ID NVARCHAR(100) PRIMARY KEY,
    SUBSCRIPTION_ID NVARCHAR(255),
    IFLOW_NAME NVARCHAR(255),
    STATUS NVARCHAR(100),
    ERROR_TYPE NVARCHAR(255),
    PAYLOAD CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS KPI_METRICS (
    ID NVARCHAR(100) PRIMARY KEY,
    METRIC_NAME NVARCHAR(255) UNIQUE,
    METRIC_VALUE DOUBLE,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_INCIDENTS_STATUS ON INCIDENTS(STATUS);
CREATE INDEX IF NOT EXISTS IDX_INCIDENTS_ERROR_TYPE ON INCIDENTS(ERROR_TYPE);
CREATE INDEX IF NOT EXISTS IDX_INCIDENTS_CREATED_AT ON INCIDENTS(CREATED_AT);
CREATE INDEX IF NOT EXISTS IDX_FAILED_MESSAGES_STATUS ON FAILED_MESSAGES(STATUS);
CREATE INDEX IF NOT EXISTS IDX_FAILED_MESSAGES_CREATED_AT ON FAILED_MESSAGES(CREATED_AT);
